name = "hello_codex"
[defaults]
builder = "docker:generic"
runner = "local:docker"

[builders."docker:generic"]
enabled = true

[runners."local:docker"]
enabled = true

[[testcases]]
name= "hello"
instances = { min = 2, default = 2, max = 200 }

[extra_sources]
  docker_generic = [
    "../../scratch"
  ]
