name = "hello_codex"
[defaults]
builder = "docker:generic"
runner = "local:docker"

[builders."docker:generic"]
enabled = true

[runners."local:docker"]
enabled = true

[[testcases]]
name= "hello_codex"
instances = { min = 2, default = 2, max = 2 }

# [testcases.params]
# payload = { type = "string", default = "Hello!" }
# count = { type = "int", default = 2 }
# printResult = { type = "bool", default = true }

[extra_sources]
  docker_generic = [
    "../../scratch"
  ]
