name: CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
permissions: {}
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: iffy/install-nim@v4
      with:
        version: binary:stable
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Install dependencies
      run: nimble install -d -y
    - name: Unit Tests
      run: nimble test
    - name: Integration Tests
      run: |
        cd vendor/dagger-contracts
        git submodule update --init .
        npm install
        npm start &
        cd ../../
        nimble testContracts
        nimble testIntegration
