# Adapted from:
# https://github.com/status-im/nim-codex/blob/main/.github/workflows/ci.yml

name: Testground
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        cache_nonce: [ 0 ] # Allows for easily busting actions/cache caches
        target:
          - os: linux
            cpu: amd64
        nim_branch: [version-1-2]
        include:
          - target:
              os: linux
            builder: ubuntu-latest
            shell: bash --noprofile --norc -eo pipefail

    defaults:
      run:
        shell: ${{ matrix.shell }} {0}
        working-directory: nim-codex

    name: '${{ matrix.target.os }}-${{ matrix.target.cpu }} (Nim ${{ matrix.nim_branch }})'
    runs-on: ${{ matrix.builder }}
    timeout-minutes: 80
    steps:
      - name: Checkout nim-codex sources
        uses: actions/checkout@v3
        with:
          path: nim-codex

      - name: Checkout Testground sources
        uses: actions/checkout@v3
        with:
          path: testground
          repository: testground/testground

      - name: APT (Linux amd64)
        if: runner.os == 'Linux' && matrix.target.cpu == 'amd64'
        run: |
          # sudo apt-fast update -qq
          # sudo DEBIAN_FRONTEND='noninteractive' apt-fast install \
          #   --no-install-recommends -yq ...

      - name: Derive environment variables
        run: |
          # Add executables built with Go to PATH
          echo "${HOME}/go/bin" >> ${GITHUB_PATH}

      # - name: Restore Testground executable from cache
      #   id: testground-exe-cache
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/go/bin/testground
      #     key: ${{ matrix.target.os }}-${{ matrix.target.cpu }}-nim-${{ matrix.nim_branch }}-${{ ... }}-cache_nonce:${{ matrix.cache_nonce }}

      # - name: Build and start Testground daemon
      #   run: |
      #     mkdir -p ${HOME}/repos && cd ${HOME}/repos
      #     git clone https://github.com/testground/testground.git && cd testground
      #     make install
      #     export PATH="${HOME}/go/bin:${PATH}"
      #     testground daemon &

      - name: Build Testground executable
        run: make install
        working-directory: testground

      - name: Start Testground executable
        run: testground daemon &

      - name: Build and run default Codex Testground plan
        run: |
          make \
            TESTGROUND_PLAN=simple_libp2p \
            TESTGROUND_OPTIONS="--instances=10 --wait" \
            testground
